### ISSUE TITLE
trace-cmd: No such file or directory

### ISSUE THREAD

**Issue by sourabhjains** [fujitsu/crash-trace#4]
Running ```trace show``` and ```trace report``` against kernel 6.3.0-rc2+ prints ```trace-cmd: No such file or directory``` .

Logs
-------
crash> extend trace.so
./trace.so: shared object loaded
crash> 
crash> trace show
trace-cmd: No such file or directory
  [ras:mc_event] function mc_event_error_type not defined
  [ucsi:ucsi_run_command] function ucsi_cmd_str not defined
  [ucsi:ucsi_reset_ppm] function ucsi_cmd_str not defined
  [ucsi:ucsi_register_altmode] function ucsi_recipient_str not defined
  [xhci-hcd:xhci_handle_event] function xhci_ring_type_string not defined
  [xhci-hcd:xhci_handle_command] function xhci_ring_type_string not defined
  [xhci-hcd:xhci_handle_transfer] function xhci_ring_type_string not defined
  [xhci-hcd:xhci_queue_trb] function xhci_ring_type_string not defined
  [xhci-hcd:xhci_dbc_handle_event] function xhci_ring_type_string not defined
  [xhci-hcd:xhci_dbc_handle_transfer] function xhci_ring_type_string not defined
  [xhci-hcd:xhci_dbc_gadget_ep_queue] function xhci_ring_type_string not defined
  [xhci-hcd:xhci_handle_cmd_stop_ep] function xhci_decode_ep_context not defined
  [xhci-hcd:xhci_handle_cmd_set_deq_ep] function xhci_decode_ep_context not defined
  [xhci-hcd:xhci_handle_cmd_reset_ep] function xhci_decode_ep_context not defined
  [xhci-hcd:xhci_handle_cmd_config_ep] function xhci_decode_ep_context not defined
  [xhci-hcd:xhci_add_endpoint] function xhci_decode_ep_context not defined
  [xhci-hcd:xhci_alloc_dev] function xhci_decode_slot_context not defined
  [xhci-hcd:xhci_free_dev] function xhci_decode_slot_context not defined
  [xhci-hcd:xhci_handle_cmd_disable_slot] function xhci_decode_slot_context not defined
  [xhci-hcd:xhci_discover_or_reset_device] function xhci_decode_slot_context not defined
  [xhci-hcd:xhci_setup_device_slot] function xhci_decode_slot_context not defined
  [xhci-hcd:xhci_handle_cmd_addr_dev] function xhci_decode_slot_context not defined
  [xhci-hcd:xhci_handle_cmd_reset_dev] function xhci_decode_slot_context not defined
  [xhci-hcd:xhci_handle_cmd_set_deq] function xhci_decode_slot_context not defined
  [xhci-hcd:xhci_configure_endpoint] function xhci_decode_slot_context not defined
  [xhci-hcd:xhci_address_ctrl_ctx] function xhci_decode_ctrl_ctx not defined
  [xhci-hcd:xhci_configure_endpoint_ctrl_ctx] function xhci_decode_ctrl_ctx not defined
  [xhci-hcd:xhci_ring_alloc] function xhci_ring_type_string not defined
  [xhci-hcd:xhci_ring_free] function xhci_ring_type_string not defined
  [xhci-hcd:xhci_ring_expansion] function xhci_ring_type_string not defined
  [xhci-hcd:xhci_inc_enq] function xhci_ring_type_string not defined
  [xhci-hcd:xhci_inc_deq] function xhci_ring_type_string not defined
  [xhci-hcd:xhci_handle_port_status] function xhci_decode_portsc not defined
  [xhci-hcd:xhci_get_port_status] function xhci_decode_portsc not defined
  [xhci-hcd:xhci_hub_status_data] function xhci_decode_portsc not defined
  [xhci-hcd:xhci_ring_ep_doorbell] function xhci_decode_doorbell not defined
  [xhci-hcd:xhci_ring_host_doorbell] function xhci_decode_doorbell not defined
  [cxl:cxl_generic_event] bad op token &
  [cxl:cxl_general_media] bad op token &
  [cxl:cxl_dram] bad op token &
  [cxl:cxl_memory_module] bad op token &
cpus=64
crash> 
crash> trace report
trace-cmd: No such file or directory
  [ras:mc_event] function mc_event_error_type not defined
  [ucsi:ucsi_run_command] function ucsi_cmd_str not defined
  [ucsi:ucsi_reset_ppm] function ucsi_cmd_str not defined
  [ucsi:ucsi_register_altmode] function ucsi_recipient_str not defined
  [xhci-hcd:xhci_handle_event] function xhci_ring_type_string not defined
  [xhci-hcd:xhci_handle_command] function xhci_ring_type_string not defined
  [xhci-hcd:xhci_handle_transfer] function xhci_ring_type_string not defined
  [xhci-hcd:xhci_queue_trb] function xhci_ring_type_string not defined
  [xhci-hcd:xhci_dbc_handle_event] function xhci_ring_type_string not defined
  [xhci-hcd:xhci_dbc_handle_transfer] function xhci_ring_type_string not defined
  [xhci-hcd:xhci_dbc_gadget_ep_queue] function xhci_ring_type_string not defined
  [xhci-hcd:xhci_handle_cmd_stop_ep] function xhci_decode_ep_context not defined
  [xhci-hcd:xhci_handle_cmd_set_deq_ep] function xhci_decode_ep_context not defined
  [xhci-hcd:xhci_handle_cmd_reset_ep] function xhci_decode_ep_context not defined
  [xhci-hcd:xhci_handle_cmd_config_ep] function xhci_decode_ep_context not defined
  [xhci-hcd:xhci_add_endpoint] function xhci_decode_ep_context not defined
  [xhci-hcd:xhci_alloc_dev] function xhci_decode_slot_context not defined
  [xhci-hcd:xhci_free_dev] function xhci_decode_slot_context not defined
  [xhci-hcd:xhci_handle_cmd_disable_slot] function xhci_decode_slot_context not defined
  [xhci-hcd:xhci_discover_or_reset_device] function xhci_decode_slot_context not defined
  [xhci-hcd:xhci_setup_device_slot] function xhci_decode_slot_context not defined
  [xhci-hcd:xhci_handle_cmd_addr_dev] function xhci_decode_slot_context not defined
  [xhci-hcd:xhci_handle_cmd_reset_dev] function xhci_decode_slot_context not defined
  [xhci-hcd:xhci_handle_cmd_set_deq] function xhci_decode_slot_context not defined
  [xhci-hcd:xhci_configure_endpoint] function xhci_decode_slot_context not defined
  [xhci-hcd:xhci_address_ctrl_ctx] function xhci_decode_ctrl_ctx not defined
  [xhci-hcd:xhci_configure_endpoint_ctrl_ctx] function xhci_decode_ctrl_ctx not defined
  [xhci-hcd:xhci_ring_alloc] function xhci_ring_type_string not defined
  [xhci-hcd:xhci_ring_free] function xhci_ring_type_string not defined
  [xhci-hcd:xhci_ring_expansion] function xhci_ring_type_string not defined
  [xhci-hcd:xhci_inc_enq] function xhci_ring_type_string not defined
  [xhci-hcd:xhci_inc_deq] function xhci_ring_type_string not defined
  [xhci-hcd:xhci_handle_port_status] function xhci_decode_portsc not defined
  [xhci-hcd:xhci_get_port_status] function xhci_decode_portsc not defined
  [xhci-hcd:xhci_hub_status_data] function xhci_decode_portsc not defined
  [xhci-hcd:xhci_ring_ep_doorbell] function xhci_decode_doorbell not defined
  [xhci-hcd:xhci_ring_host_doorbell] function xhci_decode_doorbell not defined
  [cxl:cxl_generic_event] bad op token &
  [cxl:cxl_general_media] bad op token &
  [cxl:cxl_dram] bad op token &
  [cxl:cxl_memory_module] bad op token &
cpus=64
crash> exit
[root@crash-trace]# which trace-cmd
/usr/bin/trace-cmd
[root@crash-trace]# 
[root@crash-trace]# uname -r
6.3.0-rc2+

Wondering why trace.so is not able locate trace-cmd file.

- Sourabh Jain

**Comment by sourabhjains** [comment]
```trace show``` runs ```trace-cmd report /tmp/crash.trace_dat.XXXXXX``` and since /tmp/crash.trace_dat.XXXXXX doesn't exists trace-cmd failed with the below error.

trace-cmd: No such file or directory

- Sourabh

**Comment by ted-dev-42** [comment]
same here , any update?

**Comment by sourabhjains** [comment]
Found that distro had old trace-cmd command. Installed upstream trace-cmd and the plugin started working fine:

Seems like below commit of libtraceevent fixed the issue: 

```
commit 62823da1bd46f24e2b498513a809011dfe16cd9b
Author: Steven Rostedt (VMware) <rostedt@goodmis.org>
Date:   Tue Jun 8 17:27:44 2021 -0400

    libtraceevent: Handle parsing of "(REC)->" case
    
    If a trace event wraps the special __entry variable to dereference it with
    parenthesis, it shows up in the trace event format file wrapping the
    "(REC)" as well. For example, the "func_repeats" event passed the __entry
    into a helper macro in the TP_printk() portion, and the macro correctly
    wrapped its parameter in parenthesis. This caused the output to show:
    
     "(((u64)(REC)->top_delta_ts << 32) | (REC)->bottom_delta_ts)"
    
    The parser then failed to parse the "(REC)->" portion, as it expected the
    "->" to appear directly after the "REC". This is not a requirement, and
    the parser should be able to handle such cases.
    
    When this occurred, trace-cmd would error with the following message:
    
    trace-cmd: No such file or directory
      Error: expected type 4 but read 5
    
    Link: https://lore.kernel.org/linux-trace-devel/20210608172744.796e93b7@gandalf.local.home

```

**Comment by sourabhjains** [comment]
The reported problem is unrelated to the crash-trace plugin. Therefore, this issue can be closed.
